version: "3.8"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=dbname_t7q8_user
      - POSTGRES_PASSWORD=Yz5ylpfmjVEJr8ViPP3NkoH0QRckhrNW
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
